### ISSUE TITLE
Orders show up in the store even if the order isn't completed. 

### ISSUE THREAD

**Issue by OskarOstlund** [Billmate/billmate-checkout-for-woocommerce#39]
Would you create an order and select to pay either with card or bank payment will an order be created in the store even before we have completed what is required by either Swedbank pay or trustly. This would normally not be an issue as when they are done will the order be sent to BO. However would the customer either decide against the order and close down the order or simply disconnect from the internet or get an error message will the order still remain in the store but not being there in BO. 

To test this can one complete an order and chose either Card payment or Bank payment and then either cancel the purchase midway or with the test card from Swedbank pay (card number: 5226612199533406 Expiry: 09/28 CVC: 602) chose a failed authentication status. Then without completing the order go to the orders in the woocommerce store where the order will be listed. However it will not be in BO, and with only a quick glance will it not appear any different from any other order.

**Comment by NiklasHogefjord** [comment]
@OskarOstlund This is the intended flow of the plugin.

This is similar to how other payment methods work (for instance PayPal). When the customer clicks the pay button the order is created (as a Pending order) in the e-commerce store and then, in the next step, the order is paid for.

**Comment by OskarOstlund** [comment]
Will this not result in confusion if the order fails for whatever reason? From what I can see would both a failed and a successful cardpayment show up as "inväntar betaling".

**Comment by NiklasHogefjord** [comment]
A successful card payment will get the order status "Behandlas" (eller Färdigbehandlad).

If you get "Inväntar betalning" with a successful card payment, there is something wrong. I know you have reported an issue in https://github.com/Billmate/billmate-checkout-for-woocommerce/issues/9, but that should have been fixed now. I will double check to see that all payment methods work fine.

**Comment by OskarOstlund** [comment]
Despite having pulled the latest master branches are all successful card payments still saved as "inväntar betaling".

**Comment by NiklasHogefjord** [comment]
I could not recreate the issue but I see that there was a problem in one helper function. I have fixed that now. Could you grab the latest version from Master branch and test again @OskarOstlund?

**Comment by OskarOstlund** [comment]
![image](https://user-images.githubusercontent.com/58035708/91698313-cdd04900-eb72-11ea-9463-3177446e1ade.png)
No, I still get orders saved as "Inväntar betalning". Both when I made a cardpayment as a test order or when I did it live with a real card. It does however work when I attempt to do so with an invoice payment for instance.

**Comment by NiklasHogefjord** [comment]
At the moment we can't test the card payment flow since there seem to be a problem with mixed content in BCO.

![image](https://user-images.githubusercontent.com/985946/92131042-c6749e00-ee05-11ea-9d94-e38327ff3586.png)

**Comment by NiklasHogefjord** [comment]
This should be fixed now.

**Comment by MattiasNilsson** [comment]
This is also fixed.
